apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: gcp-cloud-storage-csi-dynamic-pvc
  namespace: gcs-csi-example
spec:
  storageClassName: gcp-cloud-storage-class
  accessModes: [ "ReadWriteMany" ]
  resources:
    requests:
      storage: 5Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: gcp-cloud-storage-csi-dynamic-deployment-example
  namespace: gcs-csi-example
spec:
  replicas: 3
  selector:
    matchLabels:
      app: gcp-cloud-storage-csi-dynamic-deployment-example
  template:
    metadata:
      labels:
        app: gcp-cloud-storage-csi-dynamic-deployment-example
    spec:
      containers:
      - name: writer
        image: busybox
        resources:
          limits:
            cpu: 100m
            memory: 100Mi
          requests:
            cpu: 10m
            memory: 80Mi
        command:
          - "/bin/sh"
          - "-c"
          - touch /data/${MY_POD_NAME} && while true; do echo $(date) >> /data/${MY_POD_NAME}; sleep 1; done
        env:
          - name: MY_POD_NAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
        volumeMounts:
        - name: gcp-cloud-storage-csi-pvc
          mountPath: /data
      - name: reader
        image: busybox
        resources:
          limits:
            cpu: 100m
            memory: 100Mi
          requests:
            cpu: 10m
            memory: 80Mi
        command:
          - "/bin/sh"
          - "-c"
          - tail -f /data/${MY_POD_NAME}
        env:
          - name: MY_POD_NAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
        volumeMounts:
        - name: gcp-cloud-storage-csi-pvc
          mountPath: /data
          readOnly: true
      serviceAccountName: gcs-csi
      volumes:
      - name: gcp-cloud-storage-csi-pvc
        persistentVolumeClaim:
          claimName: gcp-cloud-storage-csi-dynamic-pvc