apiVersion: builtin
kind: ImageTagTransformer
metadata:
  name: imagetag-livenessprobe
imageTag:
  name: k8s.gcr.io/sig-storage/livenessprobe
  newTag: "v2.7.0"
---

apiVersion: builtin
kind: ImageTagTransformer
metadata:
  name: imagetag-csi-provisioner
imageTag:
  name: k8s.gcr.io/sig-storage/csi-provisioner
  newTag: "v3.2.0"
---

apiVersion: builtin
kind: ImageTagTransformer
metadata:
  name: imagetag-csi-node-registrar
imageTag:
  name: k8s.gcr.io/sig-storage/csi-node-driver-registrar
  newTag: "v2.5.1"
---

apiVersion: builtin
kind: ImageTagTransformer
metadata:
  name: imagetag-gce-cs-driver
imageTag:
  name: jiaxun/gcp-cloud-storage-csi-driver
  newTag: "v2.0.0"
---
