apiVersion: v1
kind: Pod
metadata:
  name: dlio-data-loader-{{ .Values.dlio.numFilesTrain }}-{{ .Values.dlio.recordLength }}
  annotations:
    gke-gcsfuse/volumes: "true"
    gke-gcsfuse/cpu-limit: "0"
    gke-gcsfuse/memory-limit: "0"
    gke-gcsfuse/ephemeral-storage-limit: "0"
spec:
  restartPolicy: Never
  nodeSelector:
    cloud.google.com/gke-ephemeral-storage-local-ssd: "true"
  containers:
  - name: dlio-data-loader
    image: {{ .Values.image }}
    resources:
      limits:
        cpu: "100"
        memory: 400Gi
      requests:
        cpu: "30"
        memory: 300Gi
    command:
      - "/bin/sh"
      - "-c"
      - |
        echo "Installing gsutil..."
        apt-get install -y apt-transport-https ca-certificates gnupg curl
        curl https://packages.cloud.google.com/apt/doc/apt-key.gpg | gpg --dearmor -o /usr/share/keyrings/cloud.google.gpg
        echo "deb [signed-by=/usr/share/keyrings/cloud.google.gpg] https://packages.cloud.google.com/apt cloud-sdk main" | tee -a /etc/apt/sources.list.d/google-cloud-sdk.list
        apt-get update && apt-get install google-cloud-cli

        echo "Generating data for file number: {{ .Values.dlio.numFilesTrain }}, file size: {{ .Values.dlio.recordLength }}..."

        mpirun -np 20 dlio_benchmark workload=unet3d \
        ++workload.workflow.generate_data=True \
        ++workload.workflow.train=False \
        ++workload.dataset.data_folder=/data \
        ++workload.dataset.num_files_train={{ .Values.dlio.numFilesTrain }} \
        ++workload.dataset.record_length={{ .Values.dlio.recordLength }} \
        ++workload.dataset.record_length_stdev=0 \
        ++workload.dataset.record_length_resize=0

        gsutil -m cp -R /data/train gs://{{ .Values.bucketName }}
        mkdir -p /bucket/valid
    volumeMounts:
    - name: local-dir
      mountPath: /data
    - name: gcs-fuse-csi-ephemeral
      mountPath: /bucket
  volumes:
  - name: local-dir
    emptyDir: {}
  - name: gcs-fuse-csi-ephemeral
    csi:
      driver: gcsfuse.csi.storage.gke.io
      volumeAttributes:
        bucketName: {{ .Values.bucketName }}
