apiVersion: apps/v1
kind: Deployment
metadata:
  name: gcp-gcs-csi-ephemeral-non-root-example
  namespace: gcs-csi-example
spec:
  replicas: 3
  selector:
    matchLabels:
      app: gcp-gcs-csi-ephemeral-non-root-example
  template:
    metadata:
      labels:
        app: gcp-gcs-csi-ephemeral-non-root-example
    spec:
      securityContext:
        runAsUser: 1001
        runAsGroup: 1001
        fsGroup: 1001
      containers:
      - name: writer
        image: busybox
        resources:
          limits:
            cpu: 100m
            memory: 100Mi
          requests:
            cpu: 10m
            memory: 80Mi
        command:
          - "/bin/sh"
          - "-c"
          - touch /data/${MY_POD_NAME} && while true; do echo $(date) >> /data/${MY_POD_NAME}; sleep 1; done
        env:
          - name: MY_POD_NAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
        volumeMounts:
        - name: gcp-gcs-csi-ephemeral-non-root
          mountPath: /data
      - name: reader
        image: busybox
        resources:
          limits:
            cpu: 100m
            memory: 100Mi
          requests:
            cpu: 10m
            memory: 80Mi
        command:
          - "/bin/sh"
          - "-c"
          - tail -f /data/${MY_POD_NAME}
        env:
          - name: MY_POD_NAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
        volumeMounts:
        - name: gcp-gcs-csi-ephemeral-non-root
          mountPath: /data
          readOnly: true
      serviceAccountName: gcs-csi
      volumes:
      - name: gcp-gcs-csi-ephemeral-non-root
        csi:
          driver: cloudstorage.csi.storage.gke.io
          volumeAttributes:
            bucketName: <bucket-name> # unique bucket name
            mountOptions: "allow_other,uid=1001,gid=1001"