version: 2
enable-beta-ecosystems: true
updates:
- package-ecosystem: docker
  directory: "/cmd/csi_driver"
  schedule:
    interval: weekly
- package-ecosystem: docker
  directory: "/cmd/sidecar_mounter"
  schedule:
    interval: weekly
- package-ecosystem: docker
  directory: "/cmd/webhook"
  schedule:
    interval: weekly
- package-ecosystem: gomod
  directory: "/"
  allow:
  - dependency-type: "all"
  schedule:
    interval: weekly
  groups:
    golang-dependencies:
      patterns:
        - "github.com/golang*"
    k8s-dependencies:
      patterns:
        - "k8s.io*"
        - "sigs.k8s.io*"
        - "github.com/kubernetes-csi*"
  open-pull-requests-limit: 10
