apiVersion: v1
kind: Pod
metadata:
  name: gcsfuse-csi-auth-sa
  namespace: <namespace-name>
  annotations:
    gke-gcsfuse/volumes: "true"
    gke-gcsfuse/gcp-sa-secret-name: "my-sa-secret"
spec:
  restartPolicy: Never
  containers:
  - name: busybox
    image: busybox
    resources:
      limits:
        cpu: 250m
        memory: 256Mi
      requests:
        cpu: 250m
        memory: 256Mi
    command:
      - "/bin/sh"
      - "-c"
      - tail -f /dev/null
    volumeMounts:
    - name: gcs-fuse-csi-ephemeral
      mountPath: /data
  volumes:
  - name: gcs-fuse-csi-ephemeral
    csi:
      driver: gcsfuse.csi.storage.gke.io
      volumeAttributes:
        bucketName: <bucket-name>
        skipCSIBucketAccessCheck: "true"
