apiVersion: v1
kind: Pod
metadata:
  name: my-pod5
  namespace: default
  annotations:
    gke-gcsfuse/volumes: "true" 
spec:
  terminationGracePeriodSeconds: 60 
  containers:
  - image: busybox
    name: busybox
    command: ["sleep"]
    args: ["infinity"] 
    volumeMounts:
    - name: gcs-fuse-csi-ephemeral
      mountPath: /data
      readOnly: false
    - name: gcs-fuse-csi-ephemeral2
      mountPath: /data2
      readOnly: false
  serviceAccountName: default
  volumes:
  - name: gcs-fuse-csi-ephemeral
    csi:
      driver: gcsfuse.csi.storage.gke.io
      readOnly: false
      volumeAttributes:
        bucketName: mr_chris_test
        mountOptions: "implicit-dirs" 
  - name: gcs-fuse-csi-ephemeral2
    csi:
      driver: gcsfuse.csi.storage.gke.io
      readOnly: false
      volumeAttributes:
        bucketName: mr_chris_test