// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0
// 	protoc        v3.15.1
// source: gcsfuse_proxy.proto

package pb

import (
	proto "github.com/golang/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type MountGCSRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Source           string   `protobuf:"bytes,1,opt,name=source,proto3" json:"source,omitempty"`
	Target           string   `protobuf:"bytes,2,opt,name=target,proto3" json:"target,omitempty"`
	Fstype           string   `protobuf:"bytes,3,opt,name=fstype,proto3" json:"fstype,omitempty"`
	Options          []string `protobuf:"bytes,4,rep,name=options,proto3" json:"options,omitempty"`
	SensitiveOptions []string `protobuf:"bytes,5,rep,name=sensitiveOptions,proto3" json:"sensitiveOptions,omitempty"`
}

func (x *MountGCSRequest) Reset() {
	*x = MountGCSRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_gcsfuse_proxy_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MountGCSRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MountGCSRequest) ProtoMessage() {}

func (x *MountGCSRequest) ProtoReflect() protoreflect.Message {
	mi := &file_gcsfuse_proxy_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MountGCSRequest.ProtoReflect.Descriptor instead.
func (*MountGCSRequest) Descriptor() ([]byte, []int) {
	return file_gcsfuse_proxy_proto_rawDescGZIP(), []int{0}
}

func (x *MountGCSRequest) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

func (x *MountGCSRequest) GetTarget() string {
	if x != nil {
		return x.Target
	}
	return ""
}

func (x *MountGCSRequest) GetFstype() string {
	if x != nil {
		return x.Fstype
	}
	return ""
}

func (x *MountGCSRequest) GetOptions() []string {
	if x != nil {
		return x.Options
	}
	return nil
}

func (x *MountGCSRequest) GetSensitiveOptions() []string {
	if x != nil {
		return x.SensitiveOptions
	}
	return nil
}

type PutGCPTokenRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PodID  string                 `protobuf:"bytes,1,opt,name=podID,proto3" json:"podID,omitempty"`
	Token  string                 `protobuf:"bytes,2,opt,name=token,proto3" json:"token,omitempty"`
	Expiry *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=expiry,proto3" json:"expiry,omitempty"`
}

func (x *PutGCPTokenRequest) Reset() {
	*x = PutGCPTokenRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_gcsfuse_proxy_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PutGCPTokenRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PutGCPTokenRequest) ProtoMessage() {}

func (x *PutGCPTokenRequest) ProtoReflect() protoreflect.Message {
	mi := &file_gcsfuse_proxy_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PutGCPTokenRequest.ProtoReflect.Descriptor instead.
func (*PutGCPTokenRequest) Descriptor() ([]byte, []int) {
	return file_gcsfuse_proxy_proto_rawDescGZIP(), []int{1}
}

func (x *PutGCPTokenRequest) GetPodID() string {
	if x != nil {
		return x.PodID
	}
	return ""
}

func (x *PutGCPTokenRequest) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *PutGCPTokenRequest) GetExpiry() *timestamppb.Timestamp {
	if x != nil {
		return x.Expiry
	}
	return nil
}

type GetGCPTokenExpiryRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PodID string `protobuf:"bytes,1,opt,name=podID,proto3" json:"podID,omitempty"`
}

func (x *GetGCPTokenExpiryRequest) Reset() {
	*x = GetGCPTokenExpiryRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_gcsfuse_proxy_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetGCPTokenExpiryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetGCPTokenExpiryRequest) ProtoMessage() {}

func (x *GetGCPTokenExpiryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_gcsfuse_proxy_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetGCPTokenExpiryRequest.ProtoReflect.Descriptor instead.
func (*GetGCPTokenExpiryRequest) Descriptor() ([]byte, []int) {
	return file_gcsfuse_proxy_proto_rawDescGZIP(), []int{2}
}

func (x *GetGCPTokenExpiryRequest) GetPodID() string {
	if x != nil {
		return x.PodID
	}
	return ""
}

type GetGCPTokenExpiryResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Expiry *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=expiry,proto3" json:"expiry,omitempty"`
}

func (x *GetGCPTokenExpiryResponse) Reset() {
	*x = GetGCPTokenExpiryResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_gcsfuse_proxy_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetGCPTokenExpiryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetGCPTokenExpiryResponse) ProtoMessage() {}

func (x *GetGCPTokenExpiryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_gcsfuse_proxy_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetGCPTokenExpiryResponse.ProtoReflect.Descriptor instead.
func (*GetGCPTokenExpiryResponse) Descriptor() ([]byte, []int) {
	return file_gcsfuse_proxy_proto_rawDescGZIP(), []int{3}
}

func (x *GetGCPTokenExpiryResponse) GetExpiry() *timestamppb.Timestamp {
	if x != nil {
		return x.Expiry
	}
	return nil
}

type DeleteGCPTokenRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PodID string `protobuf:"bytes,1,opt,name=podID,proto3" json:"podID,omitempty"`
}

func (x *DeleteGCPTokenRequest) Reset() {
	*x = DeleteGCPTokenRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_gcsfuse_proxy_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteGCPTokenRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteGCPTokenRequest) ProtoMessage() {}

func (x *DeleteGCPTokenRequest) ProtoReflect() protoreflect.Message {
	mi := &file_gcsfuse_proxy_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteGCPTokenRequest.ProtoReflect.Descriptor instead.
func (*DeleteGCPTokenRequest) Descriptor() ([]byte, []int) {
	return file_gcsfuse_proxy_proto_rawDescGZIP(), []int{4}
}

func (x *DeleteGCPTokenRequest) GetPodID() string {
	if x != nil {
		return x.PodID
	}
	return ""
}

var File_gcsfuse_proxy_proto protoreflect.FileDescriptor

var file_gcsfuse_proxy_proto_rawDesc = []byte{
	0x0a, 0x13, 0x67, 0x63, 0x73, 0x66, 0x75, 0x73, 0x65, 0x5f, 0x70, 0x72, 0x6f, 0x78, 0x79, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x1f, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x1b, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x65, 0x6d, 0x70, 0x74, 0x79, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x22, 0x9f, 0x01, 0x0a, 0x0f, 0x4d, 0x6f, 0x75, 0x6e, 0x74, 0x47, 0x43, 0x53,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x6f, 0x75, 0x72, 0x63,
	0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x12,
	0x16, 0x0a, 0x06, 0x74, 0x61, 0x72, 0x67, 0x65, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x06, 0x74, 0x61, 0x72, 0x67, 0x65, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x66, 0x73, 0x74, 0x79, 0x70,
	0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x66, 0x73, 0x74, 0x79, 0x70, 0x65, 0x12,
	0x18, 0x0a, 0x07, 0x6f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x18, 0x04, 0x20, 0x03, 0x28, 0x09,
	0x52, 0x07, 0x6f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x12, 0x2a, 0x0a, 0x10, 0x73, 0x65, 0x6e,
	0x73, 0x69, 0x74, 0x69, 0x76, 0x65, 0x4f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x18, 0x05, 0x20,
	0x03, 0x28, 0x09, 0x52, 0x10, 0x73, 0x65, 0x6e, 0x73, 0x69, 0x74, 0x69, 0x76, 0x65, 0x4f, 0x70,
	0x74, 0x69, 0x6f, 0x6e, 0x73, 0x22, 0x74, 0x0a, 0x12, 0x50, 0x75, 0x74, 0x47, 0x43, 0x50, 0x54,
	0x6f, 0x6b, 0x65, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x70,
	0x6f, 0x64, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x70, 0x6f, 0x64, 0x49,
	0x44, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x05, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x12, 0x32, 0x0a, 0x06, 0x65, 0x78, 0x70, 0x69, 0x72,
	0x79, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74,
	0x61, 0x6d, 0x70, 0x52, 0x06, 0x65, 0x78, 0x70, 0x69, 0x72, 0x79, 0x22, 0x30, 0x0a, 0x18, 0x47,
	0x65, 0x74, 0x47, 0x43, 0x50, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x45, 0x78, 0x70, 0x69, 0x72, 0x79,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x70, 0x6f, 0x64, 0x49, 0x44,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x70, 0x6f, 0x64, 0x49, 0x44, 0x22, 0x4f, 0x0a,
	0x19, 0x47, 0x65, 0x74, 0x47, 0x43, 0x50, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x45, 0x78, 0x70, 0x69,
	0x72, 0x79, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x32, 0x0a, 0x06, 0x65, 0x78,
	0x70, 0x69, 0x72, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f,
	0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x54, 0x69, 0x6d,
	0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x52, 0x06, 0x65, 0x78, 0x70, 0x69, 0x72, 0x79, 0x22, 0x2d,
	0x0a, 0x15, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x47, 0x43, 0x50, 0x54, 0x6f, 0x6b, 0x65, 0x6e,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x70, 0x6f, 0x64, 0x49, 0x44,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x70, 0x6f, 0x64, 0x49, 0x44, 0x32, 0x9d, 0x02,
	0x0a, 0x13, 0x47, 0x43, 0x53, 0x46, 0x75, 0x73, 0x65, 0x50, 0x72, 0x6f, 0x78, 0x79, 0x53, 0x65,
	0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x36, 0x0a, 0x08, 0x4d, 0x6f, 0x75, 0x6e, 0x74, 0x47, 0x43,
	0x53, 0x12, 0x10, 0x2e, 0x4d, 0x6f, 0x75, 0x6e, 0x74, 0x47, 0x43, 0x53, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x1a, 0x16, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x22, 0x00, 0x12, 0x3c, 0x0a,
	0x0b, 0x50, 0x75, 0x74, 0x47, 0x43, 0x50, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x12, 0x13, 0x2e, 0x50,
	0x75, 0x74, 0x47, 0x43, 0x50, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x1a, 0x16, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x62, 0x75, 0x66, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x22, 0x00, 0x12, 0x4c, 0x0a, 0x11, 0x47,
	0x65, 0x74, 0x47, 0x43, 0x50, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x45, 0x78, 0x70, 0x69, 0x72, 0x79,
	0x12, 0x19, 0x2e, 0x47, 0x65, 0x74, 0x47, 0x43, 0x50, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x45, 0x78,
	0x70, 0x69, 0x72, 0x79, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1a, 0x2e, 0x47, 0x65,
	0x74, 0x47, 0x43, 0x50, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x45, 0x78, 0x70, 0x69, 0x72, 0x79, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x42, 0x0a, 0x0e, 0x44, 0x65, 0x6c,
	0x65, 0x74, 0x65, 0x47, 0x43, 0x50, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x12, 0x16, 0x2e, 0x44, 0x65,
	0x6c, 0x65, 0x74, 0x65, 0x47, 0x43, 0x50, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x1a, 0x16, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x22, 0x00, 0x42, 0x06, 0x5a,
	0x04, 0x2e, 0x3b, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_gcsfuse_proxy_proto_rawDescOnce sync.Once
	file_gcsfuse_proxy_proto_rawDescData = file_gcsfuse_proxy_proto_rawDesc
)

func file_gcsfuse_proxy_proto_rawDescGZIP() []byte {
	file_gcsfuse_proxy_proto_rawDescOnce.Do(func() {
		file_gcsfuse_proxy_proto_rawDescData = protoimpl.X.CompressGZIP(file_gcsfuse_proxy_proto_rawDescData)
	})
	return file_gcsfuse_proxy_proto_rawDescData
}

var file_gcsfuse_proxy_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_gcsfuse_proxy_proto_goTypes = []interface{}{
	(*MountGCSRequest)(nil),           // 0: MountGCSRequest
	(*PutGCPTokenRequest)(nil),        // 1: PutGCPTokenRequest
	(*GetGCPTokenExpiryRequest)(nil),  // 2: GetGCPTokenExpiryRequest
	(*GetGCPTokenExpiryResponse)(nil), // 3: GetGCPTokenExpiryResponse
	(*DeleteGCPTokenRequest)(nil),     // 4: DeleteGCPTokenRequest
	(*timestamppb.Timestamp)(nil),     // 5: google.protobuf.Timestamp
	(*emptypb.Empty)(nil),             // 6: google.protobuf.Empty
}
var file_gcsfuse_proxy_proto_depIdxs = []int32{
	5, // 0: PutGCPTokenRequest.expiry:type_name -> google.protobuf.Timestamp
	5, // 1: GetGCPTokenExpiryResponse.expiry:type_name -> google.protobuf.Timestamp
	0, // 2: GCSFuseProxyService.MountGCS:input_type -> MountGCSRequest
	1, // 3: GCSFuseProxyService.PutGCPToken:input_type -> PutGCPTokenRequest
	2, // 4: GCSFuseProxyService.GetGCPTokenExpiry:input_type -> GetGCPTokenExpiryRequest
	4, // 5: GCSFuseProxyService.DeleteGCPToken:input_type -> DeleteGCPTokenRequest
	6, // 6: GCSFuseProxyService.MountGCS:output_type -> google.protobuf.Empty
	6, // 7: GCSFuseProxyService.PutGCPToken:output_type -> google.protobuf.Empty
	3, // 8: GCSFuseProxyService.GetGCPTokenExpiry:output_type -> GetGCPTokenExpiryResponse
	6, // 9: GCSFuseProxyService.DeleteGCPToken:output_type -> google.protobuf.Empty
	6, // [6:10] is the sub-list for method output_type
	2, // [2:6] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_gcsfuse_proxy_proto_init() }
func file_gcsfuse_proxy_proto_init() {
	if File_gcsfuse_proxy_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_gcsfuse_proxy_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MountGCSRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_gcsfuse_proxy_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PutGCPTokenRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_gcsfuse_proxy_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetGCPTokenExpiryRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_gcsfuse_proxy_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetGCPTokenExpiryResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_gcsfuse_proxy_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteGCPTokenRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_gcsfuse_proxy_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_gcsfuse_proxy_proto_goTypes,
		DependencyIndexes: file_gcsfuse_proxy_proto_depIdxs,
		MessageInfos:      file_gcsfuse_proxy_proto_msgTypes,
	}.Build()
	File_gcsfuse_proxy_proto = out.File
	file_gcsfuse_proxy_proto_rawDesc = nil
	file_gcsfuse_proxy_proto_goTypes = nil
	file_gcsfuse_proxy_proto_depIdxs = nil
}
