# Default values for data-loader.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

image: jiaxun/dlio:v1.0.0
bucketName: gke-dlio-unet3d-100kb-500k

dlio:
  numFilesTrain: 500000
  recordLength: 102400
