# Copyright 2022 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

apiVersion: v1
kind: PersistentVolume
metadata:
  name: gcp-gcs-csi-non-root-pv
spec:
  accessModes:
  - ReadWriteMany
  capacity:
    storage: 5Gi
  persistentVolumeReclaimPolicy: Retain
  storageClassName: dummy-storage-class
  claimRef:
    namespace: gcs-csi-example
    name: gcp-gcs-csi-static-non-root-pvc
  mountOptions:
    - uid=1001
    - gid=3003
  csi:
    driver: cloudstorage.csi.storage.gke.io
    volumeHandle: <bucket-name> # unique bucket name
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: gcp-gcs-csi-static-non-root-pvc
  namespace: gcs-csi-example
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
  volumeName: gcp-gcs-csi-non-root-pv
  storageClassName: dummy-storage-class
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: gcp-gcs-csi-static-non-root-example
  namespace: gcs-csi-example
spec:
  replicas: 3
  selector:
    matchLabels:
      app: gcp-gcs-csi-static-non-root-example
  template:
    metadata:
      labels:
        app: gcp-gcs-csi-static-non-root-example
    spec:
      securityContext:
        runAsUser: 1001
        runAsGroup: 2002
        fsGroup: 3003
      containers:
      - name: gke-gcsfuse-sidecar
        image: jiaxun/gcp-cloud-storage-sidecar-mounter:v0.2.0
        imagePullPolicy: Always
        securityContext:
          allowPrivilegeEscalation: false
          runAsUser: 0
          runAsGroup: 0
        args:
          - "--v=5"
        resources:
          limits:
            cpu: 100m
            memory: 30Mi
            ephemeral-storage: 5Gi
          requests:
            cpu: 100m
            memory: 30Mi
            ephemeral-storage: 5Gi
        volumeMounts:
        - mountPath: /tmp
          name: gke-gcsfuse
      - name: writer
        image: busybox
        resources:
          limits:
            cpu: 100m
            memory: 100Mi
          requests:
            cpu: 10m
            memory: 80Mi
        command:
          - "/bin/sh"
          - "-c"
          - touch /data/${MY_POD_NAME} && while true; do echo $(date) >> /data/${MY_POD_NAME}; sleep 1; done
        env:
          - name: MY_POD_NAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
        volumeMounts:
        - name: gcp-gcs-csi-pvc
          mountPath: /data
      - name: reader
        image: busybox
        resources:
          limits:
            cpu: 100m
            memory: 100Mi
          requests:
            cpu: 10m
            memory: 80Mi
        command:
          - "/bin/sh"
          - "-c"
          - tail -f /data/${MY_POD_NAME}
        env:
          - name: MY_POD_NAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
        volumeMounts:
        - name: gcp-gcs-csi-pvc
          mountPath: /data
          readOnly: true
      serviceAccountName: gcs-csi
      volumes:
      - name: gke-gcsfuse
        emptyDir: {}
      - name: gcp-gcs-csi-pvc
        persistentVolumeClaim:
          claimName: gcp-gcs-csi-static-non-root-pvc