apiVersion: v1
kind: PersistentVolume
metadata:
  name: gcp-gcs-csi-pv
spec:
  accessModes:
  - ReadWriteMany
  capacity:
    storage: 5Gi
  persistentVolumeReclaimPolicy: Retain
  storageClassName: dummy-storage-class
  claimRef:
    namespace: gcs-csi-example
    name: gcp-gcs-csi-static-pvc
  csi:
    driver: cloudstorage.csi.storage.gke.io
    volumeHandle: <bucket-name> # unique bucket name
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: gcp-gcs-csi-static-pvc
  namespace: gcs-csi-example
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
  volumeName: gcp-gcs-csi-pv
  storageClassName: dummy-storage-class
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: gcp-gcs-csi-static-example
  namespace: gcs-csi-example
spec:
  replicas: 3
  selector:
    matchLabels:
      app: gcp-gcs-csi-static-example
  template:
    metadata:
      labels:
        app: gcp-gcs-csi-static-example
    spec:
      containers:
      - name: writer
        image: busybox
        resources:
          limits:
            cpu: 100m
            memory: 100Mi
          requests:
            cpu: 10m
            memory: 80Mi
        command:
          - "/bin/sh"
          - "-c"
          - touch /data/${MY_POD_NAME} && while true; do echo $(date) >> /data/${MY_POD_NAME}; sleep 1; done
        env:
          - name: MY_POD_NAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
        volumeMounts:
        - name: gcp-gcs-csi-pvc
          mountPath: /data
      - name: reader
        image: busybox
        resources:
          limits:
            cpu: 100m
            memory: 100Mi
          requests:
            cpu: 10m
            memory: 80Mi
        command:
          - "/bin/sh"
          - "-c"
          - tail -f /data/${MY_POD_NAME}
        env:
          - name: MY_POD_NAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
        volumeMounts:
        - name: gcp-gcs-csi-pvc
          mountPath: /data
          readOnly: true
      serviceAccountName: gcs-csi
      volumes:
      - name: gcp-gcs-csi-pvc
        persistentVolumeClaim:
          claimName: gcp-gcs-csi-static-pvc