apiVersion: v1
kind: PersistentVolume
metadata:
  name: gcp-cloud-storage-csi-pv
spec:
  accessModes:
  - ReadWriteMany
  capacity:
    storage: 5Gi
  persistentVolumeReclaimPolicy: Retain
  storageClassName: dummy-storage-class
  claimRef:
    namespace: gcs-csi-example
    name: gcp-cloud-storage-csi-static-pvc
  csi:
    driver: cloudstorage.csi.storage.gke.io
    volumeHandle: <bucket-name> # unique bucket name