apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: gcp-cloud-storage-csi-static-pvc
  namespace: gcs-csi-example
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
  volumeName: gcp-cloud-storage-csi-pv
  storageClassName: dummy-storage-class