// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: proto/mounter/mounter.proto

package mounter

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type MountRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Mountpoint    string                 `protobuf:"bytes,1,opt,name=mountpoint,proto3" json:"mountpoint,omitempty"`
	VolumeID      string                 `protobuf:"bytes,2,opt,name=volumeID,proto3" json:"volumeID,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MountRequest) Reset() {
	*x = MountRequest{}
	mi := &file_proto_mounter_mounter_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MountRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MountRequest) ProtoMessage() {}

func (x *MountRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_mounter_mounter_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MountRequest.ProtoReflect.Descriptor instead.
func (*MountRequest) Descriptor() ([]byte, []int) {
	return file_proto_mounter_mounter_proto_rawDescGZIP(), []int{0}
}

func (x *MountRequest) GetMountpoint() string {
	if x != nil {
		return x.Mountpoint
	}
	return ""
}

func (x *MountRequest) GetVolumeID() string {
	if x != nil {
		return x.VolumeID
	}
	return ""
}

type MountResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MountResponse) Reset() {
	*x = MountResponse{}
	mi := &file_proto_mounter_mounter_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MountResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MountResponse) ProtoMessage() {}

func (x *MountResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_mounter_mounter_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MountResponse.ProtoReflect.Descriptor instead.
func (*MountResponse) Descriptor() ([]byte, []int) {
	return file_proto_mounter_mounter_proto_rawDescGZIP(), []int{1}
}

var File_proto_mounter_mounter_proto protoreflect.FileDescriptor

const file_proto_mounter_mounter_proto_rawDesc = "" +
	"\n" +
	"\x1bproto/mounter/mounter.proto\x12\amounter\"J\n" +
	"\fMountRequest\x12\x1e\n" +
	"\n" +
	"mountpoint\x18\x01 \x01(\tR\n" +
	"mountpoint\x12\x1a\n" +
	"\bvolumeID\x18\x02 \x01(\tR\bvolumeID\"\x0f\n" +
	"\rMountResponse2A\n" +
	"\aMounter\x126\n" +
	"\x05Mount\x12\x15.mounter.MountRequest\x1a\x16.mounter.MountResponseBBZ@github.com/GoogleCloudPlatform/gcs-fuse-csi-driver/proto/mounterb\x06proto3"

var (
	file_proto_mounter_mounter_proto_rawDescOnce sync.Once
	file_proto_mounter_mounter_proto_rawDescData []byte
)

func file_proto_mounter_mounter_proto_rawDescGZIP() []byte {
	file_proto_mounter_mounter_proto_rawDescOnce.Do(func() {
		file_proto_mounter_mounter_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_mounter_mounter_proto_rawDesc), len(file_proto_mounter_mounter_proto_rawDesc)))
	})
	return file_proto_mounter_mounter_proto_rawDescData
}

var file_proto_mounter_mounter_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_proto_mounter_mounter_proto_goTypes = []any{
	(*MountRequest)(nil),  // 0: mounter.MountRequest
	(*MountResponse)(nil), // 1: mounter.MountResponse
}
var file_proto_mounter_mounter_proto_depIdxs = []int32{
	0, // 0: mounter.Mounter.Mount:input_type -> mounter.MountRequest
	1, // 1: mounter.Mounter.Mount:output_type -> mounter.MountResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_mounter_mounter_proto_init() }
func file_proto_mounter_mounter_proto_init() {
	if File_proto_mounter_mounter_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_mounter_mounter_proto_rawDesc), len(file_proto_mounter_mounter_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_mounter_mounter_proto_goTypes,
		DependencyIndexes: file_proto_mounter_mounter_proto_depIdxs,
		MessageInfos:      file_proto_mounter_mounter_proto_msgTypes,
	}.Build()
	File_proto_mounter_mounter_proto = out.File
	file_proto_mounter_mounter_proto_goTypes = nil
	file_proto_mounter_mounter_proto_depIdxs = nil
}
