# Copyright 2018 The Kubernetes Authors.
# Copyright 2022 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
apiVersion: v1
kind: ConfigMap
metadata:
  name: bypassed-code
  namespace: gcs-csi-example
data:
  # drop the cache after each epoch to make the training job pull data via Cloud Storage FUSE
  bypassed_code.py: |2-
            os.system("sh -c 'echo 3 > /proc/sys/vm/drop_caches'")
---
apiVersion: batch/v1
kind: Job
metadata:
  name: train-job-pytorch
spec:
  backoffLimit: 0
  template:
    metadata:
      namespace: gcs-csi-example
      name: train-job-pytorch
      annotations:
        gke-gcsfuse/volumes: "true"
        gke-gcsfuse/cpu-limit: "10"
        gke-gcsfuse/memory-limit: 40Gi
        gke-gcsfuse/ephemeral-storage-limit: 20Gi
    spec:
      restartPolicy: Never
      containers:
      - name: pytorch-test
        image: nvcr.io/nvidia/pytorch:22.03-py3
        securityContext:
          privileged: true
        env:
          - name: MY_POD_NAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
        command:
          - "/bin/sh"
          - "-c"
          - git clone https://github.com/facebookresearch/dino.git;
            mkdir -p /pytorch_output;
            controller_file="/workspace/dino/main_dino.py";
            x=$(grep -n "# ============ training one epoch of DINO ... ============" $controller_file | cut -f1 -d ':');
            x=$((x - 2));
            sed -i "$x"'r /workspace/bypass-code/bypassed_code.py' $controller_file;
            pip install timm;
            python -c 'import torch;torch.hub.list("facebookresearch/xcit:main")';
            python -m torch.distributed.launch --nproc_per_node=8 $controller_file --arch vit_small --num_workers 20 --data_path /gcs/imagenet/ILSVRC/Data/CLS-LOC/train/ --output_dir /pytorch_output --norm_last_layer False --use_fp16 False --clip_grad 0 --epochs 800 --global_crops_scale 0.25 1.0 --local_crops_number 10 --local_crops_scale 0.05 0.25 --teacher_temp 0.07 --warmup_teacher_temp_epochs 30 --min_lr 0.00001  2>&1 | tee /pytorch_output/pytorch_test.log;
            mkdir -p /gcs/pytorch_output;
            cp -r /pytorch_output /gcs/pytorch_output/${MY_POD_NAME};
        resources:
          limits:
            cpu: "85"
            memory: 600Gi
            nvidia.com/gpu: "8"
          requests:
            cpu: "85"
            memory: 600Gi
            nvidia.com/gpu: "8"
        volumeMounts:
        - name: dshm
          mountPath: /dev/shm
        - name: gcs-fuse-csi-ephemeral
          mountPath: /gcs
        - name: bypassed-code
          mountPath: /workspace/bypass-code
      serviceAccountName: gcs-csi
      volumes:
      - name: dshm
        emptyDir:
          medium: Memory
          sizeLimit: 128Gi
      - name: gcs-fuse-csi-ephemeral
        csi:
          driver: gcsfuse.csi.storage.gke.io
          volumeAttributes:
            bucketName: <bucket-name>
            mountOptions: "implicit-dirs,debug_gcs,debug_fuse,debug_fs"
      - name: bypassed-code
        configMap:
          name: bypassed-code