# Copyright 2022 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

apiVersion: builtin
kind: ImageTagTransformer
metadata:
  name: imagetag-livenessprobe
imageTag:
  name: k8s.gcr.io/sig-storage/livenessprobe
  newTag: "v2.7.0"
---

apiVersion: builtin
kind: ImageTagTransformer
metadata:
  name: imagetag-csi-provisioner
imageTag:
  name: k8s.gcr.io/sig-storage/csi-provisioner
  newTag: "v3.2.0"
---

apiVersion: builtin
kind: ImageTagTransformer
metadata:
  name: imagetag-csi-node-registrar
imageTag:
  name: k8s.gcr.io/sig-storage/csi-node-driver-registrar
  newTag: "v2.5.1"
---

apiVersion: builtin
kind: ImageTagTransformer
metadata:
  name: imagetag-gce-cs-driver
imageTag:
  name: jiaxun/gcs-fuse-csi-driver
  newTag: "v0.3.0"
---
